/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "chekotqfukzbggtzvgme"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoZWtvdHFmdWt6YmdndHp2Z21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg0MTg3NzMsImV4cCI6MjEwMzk5NDc3M30.g-zZPdhorZtU0is5JhxtpklId6Cyj3g-oREfD_Zk3sI"